#! /usr/bin/env sh

jq 'del(.plugins[] | select(. == "tiddlywiki/filesystem" or . == "tiddlywiki/tiddlyweb"))' tiddlywiki.info >tiddlywiki.info.tmp

mv tiddlywiki.info.tmp tiddlywiki.info

tiddlywiki --output ./out --build index
